global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-edico-genome
  s3bucket: edico-taskcat-bucket
  regions:
    - eu-west-1
    - us-east-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-edico-genomet1:
    parameter_input: batch-params.t1.json
    template_file: dragen-master.template
    regions:
      - us-east-1
  quickstart-edico-genomet2:
    parameter_input: batch-params.t2.json
    template_file: dragen.template
    regions:
      - us-east-1
  quickstart-edico-genomet2:
    parameter_input: batch-params.t3.json
    template_file: dragen-master.template
    regions:
      - us-west-2
  quickstart-edico-genomet2:
    parameter_input: batch-params.t4.json
    template_file: dragen-master.template
    regions:
      - eu-west-1
